name: Lint

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: ChenCMD/datapack-linter@v1
        with:
          notOutputSuccess: true
          checkAlwaysAllFile: true
          # ignoreLintPathPattern: |
