name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
  push:
    branches:
      - master

env:
  PACK_NAME: enhanced-fishing
  level: ${{ inputs.level || 'patch' }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  release:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name : Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Build
        run: |
          npm i
          npm run build
      - name: Push
        run: |
          git config --local user.name "github-actions[bot]"
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "Auto build by GitHub Actions"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ env.level }}
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}'
      - name: Create Changelog
        id: create_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
              "template": "What's changed \n #{{UNCATEGORIZED}} \n\n **Full Changelog**: #{{RELEASE_DIFF}}",
              "sort": {
                "order": "DESC",
                "on_property": "mergedAt"
              }
            }
      - name: Create release file
        run: zip -r ${{ env.PACK_NAME }}-${{ steps.bump-semver.outputs.new_version }}.zip ./README.md ./data ./pack.mcmeta
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          body: ${{ steps.create_changelog.outputs.changelog }}
          files: |
            ${{ env.PACK_NAME }}-${{ steps.bump-semver.outputs.new_version }}.zip
