name: Triage

on:
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: Logerfo/triage-action@0.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
